version: '3.8'
services:
minio:
image: minio/minio:RELEASE.2025-01-01T00-00-00Z
command: server /data
environment:
MINIO_ROOT_USER: minioadmin
MINIO_ROOT_PASSWORD: minioadmin
ports:
- 9000:9000
volumes:
- minio-data:/data


rabbitmq:
image: rabbitmq:3-management
ports:
- 5672:5672
- 15672:15672


postgres:
image: postgres:15
environment:
POSTGRES_PASSWORD: changeme
ports:
- 5432:5432
volumes:
- pgdata:/var/lib/postgresql/data


api:
build: ./services/api
environment:
MINIO_ENDPOINT: minio:9000
MINIO_ACCESS_KEY: minioadmin
MINIO_SECRET_KEY: minioadmin
